[package]
name = "shhh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
regex = "1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.16"
